In [83]:
import numpy as np

In [84]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [85]:
type(b)

numpy.ndarray

Basic operation of array

In [86]:
print(a+b)
print(a-b)
print(a*b)
print(a%b)
print(a&b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1 2 3]
[0 0 2]


In [87]:
# creating a 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [88]:
#creating a 3B array
arr2 = np.array([[[1,2,3],        [4,5,6]],[[7,8,9],[10,11,12]]])
print(arr2 )

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [89]:
print(arr.shape) #shape of array


(2, 3)


In [90]:
print(arr.ndim)

2


In [91]:
print(arr.dtype)

int64


In [92]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

In [95]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [96]:
np.random.randint(10,30,size=(3,3))

array([[10, 27, 23],
       [22, 15, 18],
       [21, 18, 13]], dtype=int32)

In [97]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])
y = np.array([[1,8,2],
              [3,7,2],
              [2,5,2]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 2]
 [3 7 2]
 [2 5 2]]


In [98]:
print(x+y)
print(x-y)
print(x*y)


[[ 8 10  5]
 [ 5 12  4]
 [ 5 10  3]]
[[ 6 -6  1]
 [-1 -2  0]
 [ 1  0 -1]]
[[ 7 16  6]
 [ 6 35  4]
 [ 6 25  2]]


In [99]:
print(x@y)  #matrix multiplication

[[19 85 24]
 [21 61 18]
 [20 64 18]]


In [100]:
np.dot(x,y)#matrix multiplication

array([[19, 85, 24],
       [21, 61, 18],
       [20, 64, 18]])

In [101]:
x.prod() #product of all element in the array

np.int64(12600)

In [102]:
x.mean() #mean of all elements in the array

np.float64(3.3333333333333335)

In [103]:
y.mean() 

np.float64(3.5555555555555554)

In [104]:
round(x.mean())

3

In [105]:
x.mean(axis=0) #mean of each column

array([4., 4., 2.])

In [106]:
y.mean(axis=1)

array([3.66666667, 4.        , 3.        ])

In [107]:
print(x.sum())
print(x.var())
print(x.std())

30
3.3333333333333335
1.8257418583505538


In [108]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50))#meadian
print(np.percentile(a,25))#1st quartile
print(np.percentile(a,80))#quartile

5.0
3.0
7.4


In [109]:
b = np.random.randint(11,100,(4,4))
print(b)

[[16 23 82 63]
 [13 66 38 43]
 [29 20 79 14]
 [76 82 61 27]]


In [110]:
print('2x8')
print(b.reshape(2,8))

2x8
[[16 23 82 63 13 66 38 43]
 [29 20 79 14 76 82 61 27]]


In [111]:
print('8x2')
print(b.reshape(8,2))

8x2
[[16 23]
 [82 63]
 [13 66]
 [38 43]
 [29 20]
 [79 14]
 [76 82]
 [61 27]]


In [112]:
print(b.reshape(4,4))

[[16 23 82 63]
 [13 66 38 43]
 [29 20 79 14]
 [76 82 61 27]]


In [113]:
print(b[0])#first row
print(b[0,2])#first row , third column 
print(b[-1])#last row
print(b[1:3])#second and third row
print(b[3:])#last row 

[16 23 82 63]
82
[76 82 61 27]
[[13 66 38 43]
 [29 20 79 14]]
[[76 82 61 27]]
